import 'package:bangla_quran/model/allah_model.dart';

final List<AllahName> allahNames = [
  AllahName(
    id: 1,
    arabic: "الله",
    pronunciation: "আল্লাহ",
    meaning: "যিনি উপাসনার যোগ্য",
  ),
  AllahName(
    id: 2,
    arabic: "الرحمن",
    pronunciation: "আর-রহমান",
    meaning: "পরম দয়ালু",
  ),
  AllahName(
    id: 3,
    arabic: "الرحيم",
    pronunciation: "আর-রহীম",
    meaning: "অতিশয় দয়াবান",
  ),
  AllahName(
    id: 4,
    arabic: "الملك",
    pronunciation: "আল-মালিক",
    meaning: "সর্বময় ক্ষমতার অধিকারী",
  ),
  AllahName(
    id: 5,
    arabic: "القدوس",
    pronunciation: "আল-কুদ্দুস",
    meaning: "অতি পবিত্র",
  ),
  AllahName(
    id: 6,
    arabic: "السلام",
    pronunciation: "আস-সালাম",
    meaning: "শান্তির উৎস",
  ),
  AllahName(
    id: 7,
    arabic: "المؤمن",
    pronunciation: "আল-মু’মিন",
    meaning: "নিরাপত্তা দানকারী",
  ),
  AllahName(
    id: 8,
    arabic: "المهيمن",
    pronunciation: "আল-মুহাইমিন",
    meaning: "রক্ষাকারী ও তত্ত্বাবধায়ক",
  ),
  AllahName(
    id: 9,
    arabic: "العزيز",
    pronunciation: "আল-আজীজ",
    meaning: "পরাক্রমশালী",
  ),
  AllahName(
    id: 10,
    arabic: "الجبار",
    pronunciation: "আল-জাব্বার",
    meaning: "বলপ্রয়োগকারী",
  ),
  AllahName(
    id: 11,
    arabic: "المتكبر",
    pronunciation: "আল-মুতাকাব্বির",
    meaning: "মহিমান্বিত",
  ),
  AllahName(
    id: 12,
    arabic: "الخالق",
    pronunciation: "আল-খালিক",
    meaning: "সৃষ্টিকর্তা",
  ),
  AllahName(
    id: 13,
    arabic: "البارئ",
    pronunciation: "আল-বারি",
    meaning: "নির্মাতা",
  ),
  AllahName(
    id: 14,
    arabic: "المصور",
    pronunciation: "আল-মুসাওয়ির",
    meaning: "রূপ দানকারী",
  ),
  AllahName(
    id: 15,
    arabic: "الغفار",
    pronunciation: "আল-গফ্‌ফার",
    meaning: "অত্যন্ত ক্ষমাশীল",
  ),
  AllahName(
    id: 16,
    arabic: "القهار",
    pronunciation: "আল-কাহ্‌হার",
    meaning: "সবকিছুকে বশকারী",
  ),
  AllahName(
    id: 17,
    arabic: "الوهاب",
    pronunciation: "আল-ওয়াহ্‌হাব",
    meaning: "প্রদানকারী",
  ),
  AllahName(
    id: 18,
    arabic: "الرزاق",
    pronunciation: "আর-রজ্জাক",
    meaning: "রিজিক দানকারী",
  ),
  AllahName(
    id: 19,
    arabic: "الفتاح",
    pronunciation: "আল-ফাত্তাহ",
    meaning: "উন্মুক্তকারী",
  ),
  AllahName(
    id: 20,
    arabic: "العليم",
    pronunciation: "আল-আলীম",
    meaning: "সর্বজ্ঞ",
  ),
  AllahName(
    id: 21,
    arabic: "القابض",
    pronunciation: "আল-কাবিদ",
    meaning: "সংকুচিতকারী",
  ),
  AllahName(
    id: 22,
    arabic: "الباسط",
    pronunciation: "আল-বাসিত",
    meaning: "প্রসারিতকারী",
  ),
  AllahName(
    id: 23,
    arabic: "الخافض",
    pronunciation: "আল-খাফিদ",
    meaning: "নিম্নকারী",
  ),
  AllahName(
    id: 24,
    arabic: "الرافع",
    pronunciation: "আর-রাফি",
    meaning: "উচ্চে উঠানোকারী",
  ),
  AllahName(
    id: 25,
    arabic: "المعز",
    pronunciation: "আল-মু’ইজ্জ",
    meaning: "সম্মানদাতা",
  ),
  AllahName(
    id: 26,
    arabic: "المذل",
    pronunciation: "আল-মুজিল",
    meaning: "অপমানদাতা",
  ),
  AllahName(
    id: 27,
    arabic: "السميع",
    pronunciation: "আস-সামি'",
    meaning: "সর্বশ্রোতা",
  ),
  AllahName(
    id: 28,
    arabic: "البصير",
    pronunciation: "আল-বাসির",
    meaning: "সর্বদ্রষ্টা",
  ),
  AllahName(
    id: 29,
    arabic: "الحكم",
    pronunciation: "আল-হাকাম",
    meaning: "বিচারক",
  ),
  AllahName(
    id: 30,
    arabic: "العدل",
    pronunciation: "আল-আদল",
    meaning: "ন্যায়পরায়ণ",
  ),
  AllahName(
    id: 31,
    arabic: "اللطيف",
    pronunciation: "আল-লতীফ",
    meaning: "সদয় ও সূক্ষ্ম",
  ),
  AllahName(
    id: 32,
    arabic: "الخبير",
    pronunciation: "আল-খবীর",
    meaning: "সবজানা",
  ),
  AllahName(
    id: 33,
    arabic: "الحليم",
    pronunciation: "আল-হালীম",
    meaning: "সহনশীল",
  ),
  AllahName(
    id: 34,
    arabic: "العظيم",
    pronunciation: "আল-আযীম",
    meaning: "মহান",
  ),
  AllahName(
    id: 35,
    arabic: "الغفور",
    pronunciation: "আল-গফুর",
    meaning: "অত্যন্ত ক্ষমাশীল",
  ),
  AllahName(
    id: 36,
    arabic: "الشكور",
    pronunciation: "আশ-শাকুর",
    meaning: "কৃতজ্ঞতাপূর্ণ",
  ),
  AllahName(
    id: 37,
    arabic: "العلي",
    pronunciation: "আল-আলী",
    meaning: "অতি উচ্চ",
  ),
  AllahName(
    id: 38,
    arabic: "الكبير",
    pronunciation: "আল-কবীর",
    meaning: "মহানতম",
  ),
  AllahName(
    id: 39,
    arabic: "الحفيظ",
    pronunciation: "আল-হাফিজ",
    meaning: "সংরক্ষণকারী",
  ),
  AllahName(
    id: 40,
    arabic: "المقيت",
    pronunciation: "আল-মুকিত",
    meaning: "পুষ্টিদানকারী",
  ),
  AllahName(
    id: 41,
    arabic: "الحسيب",
    pronunciation: "আল-হাসিব",
    meaning: "হিসাব গ্রহণকারী",
  ),
  AllahName(
    id: 42,
    arabic: "الجليل",
    pronunciation: "আল-জলীল",
    meaning: "মহিমাময়",
  ),
  AllahName(
    id: 43,
    arabic: "الكريم",
    pronunciation: "আল-করীম",
    meaning: "মহাদানশীল",
  ),
  AllahName(
    id: 44,
    arabic: "الرقيب",
    pronunciation: "আর-রকীব",
    meaning: "পর্যবেক্ষণকারী",
  ),
  AllahName(
    id: 45,
    arabic: "المجيب",
    pronunciation: "আল-মুজীব",
    meaning: "প্রত্যুত্তরকারী",
  ),
  AllahName(
    id: 46,
    arabic: "الواسع",
    pronunciation: "আল-ওয়াসি",
    meaning: "সর্বব্যাপী",
  ),
  AllahName(
    id: 47,
    arabic: "الحكيم",
    pronunciation: "আল-হাকীম",
    meaning: "প্রজ্ঞাময়",
  ),
  AllahName(
    id: 48,
    arabic: "الودود",
    pronunciation: "আল-ওয়াদুদ",
    meaning: "স্নেহশীল",
  ),
  AllahName(
    id: 49,
    arabic: "المجيد",
    pronunciation: "আল-মাজীদ",
    meaning: "মহিমান্বিত",
  ),
  AllahName(
    id: 50,
    arabic: "الباعث",
    pronunciation: "আল-বা'ইস",
    meaning: "জাগ্রতকারী",
  ),
  AllahName(
    id: 51,
    arabic: "الشهيد",
    pronunciation: "আশ-শাহীদ",
    meaning: "সাক্ষী",
  ),
  AllahName(id: 52, arabic: "الحق", pronunciation: "আল-হক", meaning: "সত্য"),
  AllahName(
    id: 53,
    arabic: "الوكيل",
    pronunciation: "আল-ওয়াকিল",
    meaning: "কর্মসম্পাদনকারী",
  ),
  AllahName(
    id: 54,
    arabic: "القوي",
    pronunciation: "আল-কাউই",
    meaning: "শক্তিশালী",
  ),
  AllahName(
    id: 55,
    arabic: "المتين",
    pronunciation: "আল-মাতীন",
    meaning: "অদম্য শক্তির অধিকারী",
  ),
  AllahName(
    id: 56,
    arabic: "الولي",
    pronunciation: "আল-ওয়ালী",
    meaning: "অভিভাবক",
  ),
  AllahName(
    id: 57,
    arabic: "الحميد",
    pronunciation: "আল-হামিদ",
    meaning: "প্রশংসিত",
  ),
  AllahName(
    id: 58,
    arabic: "المحصي",
    pronunciation: "আল-মুহসী",
    meaning: "গণনাকারী",
  ),
  AllahName(
    id: 59,
    arabic: "المبدئ",
    pronunciation: "আল-মুবদী",
    meaning: "আরম্ভকারী",
  ),
  AllahName(
    id: 60,
    arabic: "المعيد",
    pronunciation: "আল-মু’ঈদ",
    meaning: "পুনরায় সৃষ্টি দানকারী",
  ),
  AllahName(
    id: 61,
    arabic: "المحيي",
    pronunciation: "আল-মুহই",
    meaning: "জীবন দানকারী",
  ),
  AllahName(
    id: 62,
    arabic: "المميت",
    pronunciation: "আল-মুমিত",
    meaning: "মৃত্যুদাতা",
  ),
  AllahName(
    id: 63,
    arabic: "الحي",
    pronunciation: "আল-হাইয়্য",
    meaning: "চিরঞ্জীব",
  ),
  AllahName(
    id: 64,
    arabic: "القيوم",
    pronunciation: "আল-কয়্যুম",
    meaning: "চিরস্থায়ী",
  ),
  AllahName(
    id: 65,
    arabic: "الواجد",
    pronunciation: "আল-ওয়াজিদ",
    meaning: "অপরিহার্য",
  ),
  AllahName(
    id: 66,
    arabic: "الماجد",
    pronunciation: "আল-মাজিদ",
    meaning: "মহিমান্বিত",
  ),
  AllahName(
    id: 67,
    arabic: "الواحد",
    pronunciation: "আল-ওয়াহিদ",
    meaning: "এক ও অদ্বিতীয়",
  ),
  AllahName(
    id: 68,
    arabic: "الصمد",
    pronunciation: "আস-সামাদ",
    meaning: "নির্ভরযোগ্য আশ্রয়স্থল",
  ),
  AllahName(
    id: 69,
    arabic: "القادر",
    pronunciation: "আল-কাদির",
    meaning: "সর্বশক্তিমান",
  ),
  AllahName(
    id: 70,
    arabic: "المقتدر",
    pronunciation: "আল-মুকতাদির",
    meaning: "অত্যন্ত ক্ষমতাবান",
  ),
  AllahName(
    id: 71,
    arabic: "المقدم",
    pronunciation: "আল-মুকাদ্দিম",
    meaning: "অগ্রগামী দানকারী",
  ),
  AllahName(
    id: 72,
    arabic: "المؤخر",
    pronunciation: "আল-মু’আখখির",
    meaning: "পিছনে রাখনেওয়ালা",
  ),
  AllahName(
    id: 73,
    arabic: "الأول",
    pronunciation: "আল-আওয়াল",
    meaning: "সবার আগে",
  ),
  AllahName(
    id: 74,
    arabic: "الآخر",
    pronunciation: "আল-আখির",
    meaning: "সবার পরে",
  ),
  AllahName(
    id: 75,
    arabic: "الظاهر",
    pronunciation: "আয-যাহির",
    meaning: "প্রকাশিত",
  ),
  AllahName(
    id: 76,
    arabic: "الباطن",
    pronunciation: "আল-বাতিন",
    meaning: "অদৃশ্য",
  ),
  AllahName(
    id: 77,
    arabic: "الوالي",
    pronunciation: "আল-ওয়ালী",
    meaning: "পরিচালনাকারী",
  ),
  AllahName(
    id: 78,
    arabic: "المتعالي",
    pronunciation: "আল-মুতাআলি",
    meaning: "উচ্চ মর্যাদাসম্পন্ন",
  ),
  AllahName(
    id: 79,
    arabic: "البر",
    pronunciation: "আল-বার",
    meaning: "অত্যন্ত কল্যাণকামী",
  ),
  AllahName(
    id: 80,
    arabic: "التواب",
    pronunciation: "আত-তাওয়াব",
    meaning: "তাওবা কবুলকারী",
  ),
  AllahName(
    id: 81,
    arabic: "المنتقم",
    pronunciation: "আল-মুনতাকিম",
    meaning: "প্রতিশোধ গ্রহণকারী",
  ),
  AllahName(
    id: 82,
    arabic: "العفو",
    pronunciation: "আল-আফু",
    meaning: "ক্ষমাকারী",
  ),
  AllahName(
    id: 83,
    arabic: "الرؤوف",
    pronunciation: "আর-রউফ",
    meaning: "অত্যন্ত দয়ালু",
  ),
  AllahName(
    id: 84,
    arabic: "مالك الملك",
    pronunciation: "মালিকুল-মুলক",
    meaning: "সার্বভৌম রাজ্যের অধিপতি",
  ),
  AllahName(
    id: 85,
    arabic: "ذو الجلال والإكرام",
    pronunciation: "যুল-জালালি ওয়াল-ইকরাম",
    meaning: "মহিমা ও মর্যাদার অধিকারী",
  ),
  AllahName(
    id: 86,
    arabic: "المقسط",
    pronunciation: "আল-মুকসিত",
    meaning: "ন্যায়বিচারকারী",
  ),
  AllahName(
    id: 87,
    arabic: "الجامع",
    pronunciation: "আল-জামি",
    meaning: "একত্রকারী",
  ),
  AllahName(
    id: 88,
    arabic: "الغني",
    pronunciation: "আল-গনী",
    meaning: "অমুখাপেক্ষী",
  ),
  AllahName(
    id: 89,
    arabic: "المغني",
    pronunciation: "আল-মুগনী",
    meaning: "সম্পদদানকারী",
  ),
  AllahName(
    id: 90,
    arabic: "المانع",
    pronunciation: "আল-মানি",
    meaning: "বাধা প্রদানকারী",
  ),
  AllahName(
    id: 91,
    arabic: "الضار",
    pronunciation: "আদ-দার",
    meaning: "ক্ষতিকর",
  ),
  AllahName(
    id: 92,
    arabic: "النافع",
    pronunciation: "আন-নাফি",
    meaning: "উপকারী",
  ),
  AllahName(
    id: 93,
    arabic: "النور",
    pronunciation: "আন-নূর",
    meaning: "আলোকদাতা",
  ),
  AllahName(
    id: 94,
    arabic: "الهادي",
    pronunciation: "আল-হাদী",
    meaning: "পথপ্রদর্শক",
  ),
  AllahName(
    id: 95,
    arabic: "البديع",
    pronunciation: "আল-বাদী'",
    meaning: "নব সৃষ্টিকারী",
  ),
  AllahName(
    id: 96,
    arabic: "الباقي",
    pronunciation: "আল-বাকী",
    meaning: "চিরস্থায়ী",
  ),
  AllahName(
    id: 97,
    arabic: "الوارث",
    pronunciation: "আল-ওয়ারিস",
    meaning: "উত্তরাধিকারী",
  ),
  AllahName(
    id: 98,
    arabic: "الرشيد",
    pronunciation: "আর-রশিদ",
    meaning: "সঠিক পথপ্রদর্শক",
  ),
  AllahName(
    id: 99,
    arabic: "الصبور",
    pronunciation: "আস-সবুর",
    meaning: "অত্যন্ত ধৈর্যশীল",
  ),
];
